const assert = require('node:assert/strict');
const test = require('node:test');
const { MAIN_BUNDLE_ID, updateSource, validateMetadata } = require('./sidestore-source');
const SHA = '1234567890abcdef1234567890abcdef12345678';
function metadata(channel, n, overrides = {}) { return { channel, ...(channel === 'pr' ? { prNumber: n, title: `PR ${n}`, htmlURL: `https://github.com/louismollick/substreamer/pull/${n}` } : {}), headSHA: SHA, bundleIdentifier: channel === 'main' ? MAIN_BUNDLE_ID : `com.louismollick.substreamer.pr${n}`, version: channel === 'main' ? '8.0.91' : `0.${n}.4`, buildVersion: '1042.1', date: '2026-08-05T12:00:00Z', downloadURL: 'https://example.com/app.ipa', size: 123, minOSVersion: '15.1', privacy: {}, ...overrides }; }
test('creates first source with featured main', () => { const s = updateSource(null, 'upsert-main', metadata('main')); assert.deepEqual(s.apps.map(a => a.bundleIdentifier), [MAIN_BUNDLE_ID]); assert.deepEqual(s.featuredApps, [MAIN_BUNDLE_ID]); });
test('retains main, orders PRs descending, and replaces only selected entry', () => { let s = updateSource(null, 'upsert-main', metadata('main')); s = updateSource(s, 'upsert-pr', metadata('pr', 3)); s = updateSource(s, 'upsert-pr', metadata('pr', 9)); s = updateSource(s, 'upsert-pr', metadata('pr', 3, { version: '0.3.5' })); assert.deepEqual(s.apps.map(a => a.bundleIdentifier), [MAIN_BUNDLE_ID, 'com.louismollick.substreamer.pr9', 'com.louismollick.substreamer.pr3']); assert.equal(s.apps[2].versions[0].version, '0.3.5'); assert.equal(s.apps[2].versions.length, 1); });
test('updates main without changing PR', () => { let s = updateSource(null, 'upsert-pr', metadata('pr', 2)); s = updateSource(s, 'upsert-main', metadata('main', null, { buildVersion: '1043.1' })); assert.equal(s.apps[1].bundleIdentifier, 'com.louismollick.substreamer.pr2'); });
test('remove is idempotent and recalculates featured apps', () => { let s = updateSource(null, 'upsert-main', metadata('main')); s = updateSource(s, 'upsert-pr', metadata('pr', 4)); s = updateSource(s, 'remove-pr', 4); s = updateSource(s, 'remove-pr', 4); assert.deepEqual(s.featuredApps, [MAIN_BUNDLE_ID]); });
test('rejects invalid metadata and bundle IDs', () => { assert.throws(() => validateMetadata(metadata('pr', 2, { bundleIdentifier: 'bad' }), 'upsert-pr'), /bundleIdentifier/); assert.throws(() => validateMetadata(metadata('main', null, { headSHA: 'short' }), 'upsert-main'), /40-character/); assert.throws(() => validateMetadata(metadata('main', null, { size: 0 }), 'upsert-main'), /size/); assert.throws(() => validateMetadata(metadata('main', null, { privacy: [] }), 'upsert-main'), /privacy/); assert.throws(() => validateMetadata(metadata('main', null, { downloadURL: 'bad' }), 'upsert-main'), /HTTPS/); });
test('rejects malformed existing source', () => assert.throws(() => updateSource({ apps: 'bad' }, 'upsert-main', metadata('main')), /apps array/));
